/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"
#include "gpio.h"
#include "spi.h"
#include "lcd.h"



int main(void)
{
	gpio_init();
	spi_gpio_init();
	cs_disable();
	spi1_config();
	lcd_init();

//	for (int y = 0; y < LCD_HEIGHT; y++) {
//	  for (int x = 0; x < LCD_WIDTH; x++) {
//	    lcd_put_pixel(x, y, __REV16(x / 10 + y * 16));
//	  }
//	}
//	lcd_copy();

	for (int y = 0; y < LCD_HEIGHT; y++) {
	  for (int x = 0; x < LCD_WIDTH; x++) {
	    lcd_put_pixel(x, y, 1);
	  }
	}
	lcd_copy();

	while (1)
	{

	}
}
